version: '3'
services:
    node-red:
        build: node-red/.
        # Ports disabled for internal deployment
        # ports:
        #     - "1880:1880"
    custom-flow:
        build: deploy_flow/.
        depends_on:
            - "node-red"
        links:
            - "node-red"
        command: ["./wait-for.sh", "node-red:1880", "--", "python3", "app.py"]